---

- name: debian | add mariadb key
  apt_key: "id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xcbcb082a1bb943db state=present"

- name: debian | add mariadb repository
  apt_repository: repo='deb http://mirror.i3d.net/pub/mariadb/repo/5.5/debian wheezy main' state=present update_cache=no

- name: debian | add mariadb source repository
  apt_repository: repo='deb-src http://mirror.i3d.net/pub/mariadb/repo/5.5/debian wheezy main' state=present update_cache=yes

- name: debian | install mariadb
  apt: pkg=mariadb-server state=present
  register: installed_mariadb

- name: debian | install python-mysqldb
  apt: pkg=mariadb-server state=present

- name: debian | write my.cnf
  template: "src=my.cnf.debian.j2 dest={{ mariadb_config }} owner=root group=root mode=0644"
  notify:
    - restart mariadb
