---

- name: add mariadb key
  apt_key: "id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xcbcb082a1bb943db state=present"

- name: add mariadb repository
  apt_repository: "repo='deb http://mirror.i3d.net/pub/mariadb/repo/5.5/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main' state=present update_cache=no"

- name: add mariadb source repository
  apt_repository: "repo='deb-src http://mirror.i3d.net/pub/mariadb/repo/5.5/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main' state=present update_cache=yes"

  # This give packages from the mariadb repository a higher priority
  # It has happened before that mariadb keeps mysql libraries backs
- name: copy the apt-preferences file
  copy: src=50_mariadb dest=/etc/apt/preferences.d/50_mariadb

- name: remove libmysqlclient18 if it already exists
  apt: pkg=libmysqlclient18 state=absent
  
- name: install mariadb
  apt: pkg=mariadb-server state=present
  register: installed_mariadb

- name: install python-mysqldb
  apt: pkg=python-mysqldb state=present

- name: stop mariadb
  service: name=mysql state=stopped

- name: write my.cnf
  template: "src=my.cnf.j2 dest={{ mariadb_config }} owner=root group=root mode=0644"

- name: remove old log files
  file: "path={{ item }} state=absent"
  with_items:
    - /var/log/mysql.err
    - /var/log/mysql.log

- name: create new data dir
  command: "{{ mariadb_install_db_bin }} --basedir={{ mariadb_base_dir }} --datadir={{ mariadb_data_dir }} --user=mysql"
  when: mariadb_data_dir != '/var/lib/mysql'

- name: start mariadb
  service: name=mysql enabled=yes state=started
  register: started_mariadb

- name: temporarily remove root/.my.cnf
  file: path=/root/.my.cnf state=absent
  when: installed_mariadb|changed

- name: prepare secure mariadb
  template: src=mariadb_init.sql.j2 dest=/tmp/mariadb_init.sql owner=root group=root mode=0600
  when: installed_mariadb|changed

- name: secure mariadb
  shell: mysql mysql < /tmp/mariadb_init.sql
  when: installed_mariadb|changed

- name: cleanup secure mariadb
  file: path=/tmp/mariadb_init.sql state=absent
  when: installed_mariadb|changed

- name: write root/.my.cnf
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
